# Generated by Django 5.0.3 on 2024-03-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="slug",
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["slug"], name="shortener_u_slug_0cb73a_idx"),
        ),
    ]
